In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50])

In [3]:
print("Numpy Array:")
print(arr)

Numpy Array:
[10 20 30 40 50]


In [4]:
print("\n --- Array Indexing---")

print("First element:", arr[0])
print("Third element:", arr[2])
print("Last element:", arr[-1])


 --- Array Indexing---
First element: 10
Third element: 30
Last element: 50


In [6]:
print("\n--- Array Slicing---")

print("First three elements:", arr[0:3])
print("Elements from indexx 2:", arr[2:])
print("Last three elements:", arr[-3:])


--- Array Slicing---
First three elements: [10 20 30]
Elements from indexx 2: [30 40 50]
Last three elements: [30 40 50]


In [7]:
print("\n--- Basic Array Operations---")

print("Add 5:", arr +5)
print("Subtract 5:", arr - 5)
print("Muliple by 2:", arr * 2)
print("Divide by 10:", arr / 10)


--- Basic Array Operations---
Add 5: [15 25 35 45 55]
Subtract 5: [ 5 15 25 35 45]
Muliple by 2: [ 20  40  60  80 100]
Divide by 10: [1. 2. 3. 4. 5.]


In [9]:
print("\n---Mathematial Operations---")
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))


---Mathematial Operations---
Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10


In [10]:
print("Original Array shape:")
print(np.shape(arr))
print(arr)

print("\n---Array Reshaping---")
reshaped_arr = arr.reshape(5,1)

print("Reshaped Array:")
print(reshaped_arr)

Original Array shape:
(5,)
[10 20 30 40 50]

---Array Reshaping---
Reshaped Array:
[[10]
 [20]
 [30]
 [40]
 [50]]


In [11]:
import pandas as pd

In [14]:
data = {
    "Name" : ["Asha","Ravi","Meera",'Kiran'],
    "MArks" : [88,72,91,65],
    "Branch" : ["CSE", "ESE", "CSE", "ISE"]
}

In [20]:
df= pd.DataFrame(data)

print(("\n---Pandas DataFrame---"))
print(df)


---Pandas DataFrame---
    Name  MArks Branch
0   Asha     88    CSE
1   Ravi     72    ESE
2  Meera     91    CSE
3  Kiran     65    ISE


In [23]:
print("\n---Row Indexing---")

print("First Row:")
print(df.iloc[0])

print("\n Third Row:")
print(df.iloc[2])


---Row Indexing---
First Row:
Name      Asha
MArks       88
Branch     CSE
Name: 0, dtype: object

 Third Row:
Name      Meera
MArks        91
Branch      CSE
Name: 2, dtype: object


In [24]:
print("\n---Colum Indexing---")

print("")


---Colum Indexing---



In [25]:
print("\n---Specific value---")

print("marks of first Student:",df.iloc[0,1])


---Specific value---
marks of first Student: 88


In [26]:
print("\n ---Row and Colun SLicing---")

print("First three rows with Name and MArks:")
print(df.iloc[0:3,[0,1]])


 ---Row and Colun SLicing---
First three rows with Name and MArks:
    Name  MArks
0   Asha     88
1   Ravi     72
2  Meera     91


In [28]:
print("\n---Data Filtering---")

result= df[df["MArks"] > 70]

print("Student with marks greater than 70")
print(result)


---Data Filtering---
Student with marks greater than 70
    Name  MArks Branch
0   Asha     88    CSE
1   Ravi     72    ESE
2  Meera     91    CSE
